spring:
    profiles:
        active: dev
    datasource:
        url: jdbc:h2:file:./target/h2db/db/filerouge
        username: filerouge
        password:
        driverClassName: org.h2.Driver
    h2:
        console:
            enabled: false
    jpa:
        hibernate.ddl-auto: update
        database: H2
        show-sql: true